version: '3.8'

services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.saudu.com.br
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - ENABLE_RSPAMD=0
      - ENABLE_OPENDKIM=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - SSL_TYPE=letsencrypt
      - POSTMASTER_ADDRESS=postmaster@saudu.com.br
      - TZ=America/Sao_Paulo
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      mailnet:
        aliases:
          - mail.saudu.com.br

  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    depends_on:
      - mailserver
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      # Apontar para o FQDN com IMAPS explícito
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls//mail.saudu.com.br
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      # Apontar para o FQDN com certificado válido
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://mail.saudu.com.br
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_USERNAME_DOMAIN=saudu.com.br
      - ROUNDCUBEMAIL_PLUGINS=archive,zipdownload
      - TZ=America/Sao_Paulo
      # Adicionado para corrigir o erro de login (verificação SSL)
      - ROUNDCUBEMAIL_IMAP_VERIFY_PEER=false
      - ROUNDCUBEMAIL_SMTP_VERIFY_PEER=false
    volumes:
      - ./docker-data/roundcube/db/:/var/roundcube/db/
    ports:
      - "8081:80"
    restart: always
    networks:
      - mailnet

# Seção adicionada para criar a rede interna
networks:
  mailnet:
    driver: bridge